#!/bin/bash
set -e

PROJECT_DIR="$HOME/Projects/SabtHazineha"
VENV_DIR="$HOME/Projects/SabtHazineha_venv_ios"
OUTPUT_DIR="$HOME/Projects/SabtHazineha_ios_outputs"

BUILD_NUMBER="23"
BUILD_VERSION="1.0.16"

echo "========== Costio iOS IPA Build =========="
echo "PROJECT_DIR=$PROJECT_DIR"
echo "VENV_DIR=$VENV_DIR"
echo "OUTPUT_DIR=$OUTPUT_DIR"
echo "BUILD_VERSION=$BUILD_VERSION"
echo "BUILD_NUMBER=$BUILD_NUMBER"
echo "=========================================="

cd "$PROJECT_DIR"

deactivate 2>/dev/null || true

echo "========== 1) Create/activate venv =========="
if [ ! -d "$VENV_DIR" ]; then
  python3.13 -m venv "$VENV_DIR"
fi

source "$VENV_DIR/bin/activate"

which python
python -m pip install --upgrade pip

echo "========== 2) iOS config =========="

cp pyproject_ios.toml pyproject.toml
cp requirements_ios.txt requirements.txt

echo "Updating pyproject.toml version/build number..."
python - <<EOF
from pathlib import Path
import re

path = Path("pyproject.toml")
text = path.read_text()

build_version = "$BUILD_VERSION"
build_number = "$BUILD_NUMBER"

text = re.sub(
    r'(?m)^version\s*=\s*"[^"]+"',
    f'version = "{build_version}"',
    text,
    count=1,
)

text = re.sub(
    r'(?m)^build_number\s*=\s*\d+',
    f'build_number = {build_number}',
    text,
    count=1,
)

path.write_text(text)

print("Updated pyproject.toml:")
print(f"version = {build_version}")
print(f"build_number = {build_number}")
EOF

echo "Current pyproject version:"
grep -n "version =\|build_number" pyproject.toml

echo "========== 2.5) Update app_config.py =========="

cat > "$PROJECT_DIR/app_config.py" <<EOF_CONFIG
# Auto-generated by build_ios_ipa.sh
# Do not edit manually; update BUILD_VERSION and BUILD_NUMBER in the build script.

APP_VERSION = "$BUILD_VERSION"
BUILD_NUMBER = "$BUILD_NUMBER"
EOF_CONFIG

echo "Updated app_config.py:"
cat "$PROJECT_DIR/app_config.py"

echo "========== 2.6) Install requirements =========="
python -m pip install -r requirements.txt

echo "========== 3) Compile check =========="
python -m py_compile app_config.py
python -m py_compile main.py
python -m py_compile ui/profile_view.py
python -m py_compile services/voice_service_router.py

if [ -f "services/voice_service_ios.py" ]; then
  python -m py_compile services/voice_service_ios.py
fi

echo "========== 4) Clean old build =========="
rm -rf build

export COPYFILE_DISABLE=1
find "$PROJECT_DIR" -name "._*" -delete
find "$PROJECT_DIR" -name ".DS_Store" -delete
xattr -cr "$PROJECT_DIR"

echo "========== 5) Flet iOS IPA build =========="

flet build ipa . -v \
  --project costio \
  --product Costio \
  --org com.pps \
  --bundle-id com.pps.costio \
  --build-number "$BUILD_NUMBER" \
  --build-version "$BUILD_VERSION" \
  --no-ios-splash \
  --skip-flutter-doctor

echo "========== 6) Copy final IPA outside project =========="
mkdir -p "$OUTPUT_DIR"

IPA_PATH=""

if [ -f "$PROJECT_DIR/build/ipa/costio.ipa" ]; then
  IPA_PATH="$PROJECT_DIR/build/ipa/costio.ipa"
elif [ -f "$PROJECT_DIR/build/flutter/build/ios/ipa/costio.ipa" ]; then
  IPA_PATH="$PROJECT_DIR/build/flutter/build/ios/ipa/costio.ipa"
else
  IPA_PATH=$(find "$PROJECT_DIR/build" -name "*.ipa" -print | head -1)
fi

echo "IPA_PATH=$IPA_PATH"

if [ -n "$IPA_PATH" ] && [ -f "$IPA_PATH" ]; then
  FINAL_IPA="$OUTPUT_DIR/costio-$BUILD_VERSION-$BUILD_NUMBER.ipa"
  cp "$IPA_PATH" "$FINAL_IPA"
  echo "Copied final IPA:"
  ls -lh "$FINAL_IPA"
else
  echo "ERROR: Final IPA not found."
  echo "Available IPA files:"
  find "$PROJECT_DIR/build" -name "*.ipa" -print
  exit 1
fi

echo "========== 7) Size check =========="
du -sh "$PROJECT_DIR/build" 2>/dev/null || true
du -sh "$FINAL_IPA" 2>/dev/null || true

echo "========== DONE =========="
echo "Final IPA:"
echo "$FINAL_IPA"