#!/bin/bash
set -e

export PATH="$HOME/flutter/3.41.4/bin:/opt/homebrew/opt/openjdk/bin:/opt/homebrew/opt/python@3.13/libexec/bin:/opt/homebrew/opt/python@3.13/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"


PROJECT_DIR="$HOME/Projects/SabtHazineha"
VENV_DIR="$HOME/Projects/SabtHazineha_venv_android"
OUTPUT_DIR="$HOME/Projects/SabtHazineha_android_outputs"

BUILD_NUMBER="23"
BUILD_VERSION="1.0.16"

KEYSTORE_PATH="$HOME/Projects/SabtHazineha/keys/upload-keystore.jks"
KEY_ALIAS="upload"
KEYSTORE_PASSWORD="Parisa@Parham0211"
KEY_PASSWORD="Parisa@Parham0211"

echo "========== Costio Android APK Build =========="
echo "PROJECT_DIR=$PROJECT_DIR"
echo "VENV_DIR=$VENV_DIR"
echo "OUTPUT_DIR=$OUTPUT_DIR"
echo "BUILD_VERSION=$BUILD_VERSION"
echo "BUILD_NUMBER=$BUILD_NUMBER"
echo "KEYSTORE_PATH=$KEYSTORE_PATH"
echo "=============================================="

cd "$PROJECT_DIR"

deactivate 2>/dev/null || true

echo "========== 1) Create/activate venv =========="
if [ ! -d "$VENV_DIR" ]; then
  python3.13 -m venv "$VENV_DIR"
fi

source "$VENV_DIR/bin/activate"

which python
python -m pip install --upgrade pip

echo "========== 2) Android config =========="
cp pyproject_android.toml pyproject.toml
cp requirements_android.txt requirements.txt

echo "Updating pyproject.toml version/build number..."
python - <<EOF_PY
from pathlib import Path
import re

path = Path("pyproject.toml")
text = path.read_text()

build_version = "$BUILD_VERSION"
build_number = "$BUILD_NUMBER"

text = re.sub(
    r'(?m)^version\s*=\s*"[^"]+"',
    f'version = "{build_version}"',
    text,
    count=1,
)

text = re.sub(
    r'(?m)^build_number\s*=\s*\d+',
    f'build_number = {build_number}',
    text,
    count=1,
)

path.write_text(text)

print("Updated pyproject.toml:")
print(f"version = {build_version}")
print(f"build_number = {build_number}")
EOF_PY

grep -n "version =\|build_number" pyproject.toml

echo "========== 2.5) Update app_config.py =========="

cat > "$PROJECT_DIR/app_config.py" <<EOF_CONFIG
# Auto-generated by build_android_apk.sh
# Do not edit manually; update BUILD_VERSION and BUILD_NUMBER in the build script.

APP_VERSION = "$BUILD_VERSION"
BUILD_NUMBER = "$BUILD_NUMBER"
EOF_CONFIG

echo "Updated app_config.py:"
cat "$PROJECT_DIR/app_config.py"

echo "========== 2.6) Install requirements =========="

python -m pip install -r requirements.txt

echo "========== 3) Compile check =========="
python -m py_compile main.py
python -m py_compile services/voice_service_router.py
python -m py_compile services/voice_service_android.py

echo "========== 4) Clean old build =========="
rm -rf build

export COPYFILE_DISABLE=1
find "$PROJECT_DIR" -name "._*" -delete
find "$PROJECT_DIR" -name ".DS_Store" -delete
xattr -cr "$PROJECT_DIR"

echo "========== 5) Java setup =========="
export JAVA_HOME="/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"
export PATH="$JAVA_HOME/bin:$PATH"

echo "JAVA_HOME=$JAVA_HOME"
which java
java -version

echo "========== 6) Signing setup =========="
if [ ! -f "$KEYSTORE_PATH" ]; then
  echo "ERROR: Keystore not found at: $KEYSTORE_PATH"
  exit 1
fi

export FLET_ANDROID_SIGNING_KEY_STORE="$KEYSTORE_PATH"
export FLET_ANDROID_SIGNING_KEY_ALIAS="$KEY_ALIAS"
export FLET_ANDROID_SIGNING_KEY_STORE_PASSWORD="$KEYSTORE_PASSWORD"
export FLET_ANDROID_SIGNING_KEY_PASSWORD="$KEY_PASSWORD"

echo "========== 7) First Flet APK build =========="
flet build apk . -v \
  --project costio \
  --product Costio \
  --org com.pps \
  --bundle-id com.pps.costio \
  --build-number "$BUILD_NUMBER" \
  --build-version "$BUILD_VERSION" \
  --skip-flutter-doctor

echo "========== 8) Copy custom Android files =========="

if [ -f "$PROJECT_DIR/flutter_android/AndroidManifest.xml" ]; then
  cp "$PROJECT_DIR/flutter_android/AndroidManifest.xml" \
     "$PROJECT_DIR/build/flutter/android/app/src/main/AndroidManifest.xml"
  echo "Copied AndroidManifest.xml"
else
  echo "SKIP: flutter_android/AndroidManifest.xml not found"
fi

if [ -f "$PROJECT_DIR/flutter_android/build.gradle.kts" ]; then
  cp "$PROJECT_DIR/flutter_android/build.gradle.kts" \
     "$PROJECT_DIR/build/flutter/android/app/build.gradle.kts"
  echo "Copied build.gradle.kts"
else
  echo "SKIP: flutter_android/build.gradle.kts not found"
fi

MAIN_ACTIVITY_TARGET="$PROJECT_DIR/build/flutter/android/app/src/main/kotlin/com/pps/costio/MainActivity.kt"
mkdir -p "$(dirname "$MAIN_ACTIVITY_TARGET")"

if [ -f "$PROJECT_DIR/flutter_android/MainActivity.kt" ]; then
  cp "$PROJECT_DIR/flutter_android/MainActivity.kt" "$MAIN_ACTIVITY_TARGET"
  echo "Copied MainActivity.kt"
else
  echo "SKIP: flutter_android/MainActivity.kt not found"
fi

echo "Writing Mac local.properties"

FLUTTER_BIN="$(which flutter)"
FLUTTER_SDK="$(cd "$(dirname "$FLUTTER_BIN")/.." && pwd)"
ANDROID_SDK="$HOME/Android/sdk"

export ANDROID_HOME="$ANDROID_SDK"
export ANDROID_SDK_ROOT="$ANDROID_SDK"

cat > "$PROJECT_DIR/build/flutter/android/local.properties" <<EOF_LOCAL
sdk.dir=$ANDROID_SDK
flutter.sdk=$FLUTTER_SDK
flutter.buildMode=release
flutter.versionName=$BUILD_VERSION
flutter.versionCode=$BUILD_NUMBER
EOF_LOCAL

cat "$PROJECT_DIR/build/flutter/android/local.properties"

echo "========== 9) Rebuild APK after Android patches =========="
cd "$PROJECT_DIR/build/flutter/android"

export JAVA_HOME="/opt/homebrew/opt/openjdk@17/libexec/openjdk.jdk/Contents/Home"
export PATH="$JAVA_HOME/bin:$PATH"

export ANDROID_SDK="$HOME/Android/sdk"
export ANDROID_HOME="$ANDROID_SDK"
export ANDROID_SDK_ROOT="$ANDROID_SDK"

echo "JAVA_HOME=$JAVA_HOME"
which java
java -version
echo "ANDROID_HOME=$ANDROID_HOME"

export SERIOUS_PYTHON_SITE_PACKAGES="$PROJECT_DIR/build/site-packages"

./gradlew clean
./gradlew assembleRelease

echo "========== 10) Copy final APK outside project =========="
mkdir -p "$OUTPUT_DIR"

APK_PATH=""

if [ -f "$PROJECT_DIR/build/flutter/build/app/outputs/flutter-apk/app-release.apk" ]; then
  APK_PATH="$PROJECT_DIR/build/flutter/build/app/outputs/flutter-apk/app-release.apk"
elif [ -f "$PROJECT_DIR/build/flutter/android/app/build/outputs/apk/release/app-release.apk" ]; then
  APK_PATH="$PROJECT_DIR/build/flutter/android/app/build/outputs/apk/release/app-release.apk"
else
  APK_PATH=$(find "$PROJECT_DIR/build" -name "app-release.apk" -print | head -1)
fi

echo "APK_PATH=$APK_PATH"

if [ -n "$APK_PATH" ] && [ -f "$APK_PATH" ]; then
  FINAL_APK="$OUTPUT_DIR/costio-$BUILD_VERSION-$BUILD_NUMBER.apk"
  cp "$APK_PATH" "$FINAL_APK"
  echo "Copied final APK:"
  ls -lh "$FINAL_APK"
else
  echo "ERROR: Final app-release.apk not found."
  echo "Available APK files:"
  find "$PROJECT_DIR/build" -name "*.apk" -print
  exit 1
fi

echo "========== 11) Size check =========="
du -sh "$PROJECT_DIR/build" 2>/dev/null || true
du -sh "$FINAL_APK" 2>/dev/null || true

echo "========== DONE =========="
echo "Final APK:"
echo "$FINAL_APK"



# find "$PROJECT_DIR" -name "__pycache__" -type d -prune -exec rm -rf {} +
# find "$PROJECT_DIR" -name "*.pyc" -delete
# find "$PROJECT_DIR" -name "*.pyo" -delete
# find "$PROJECT_DIR" -name "*.m4a" -delete
# find "$PROJECT_DIR" -name "*.wav" -delete
# find "$PROJECT_DIR" -name "*.mp3" -delete
# find "$PROJECT_DIR" -name "*.mp4" -delete